---
title: "TP1: The Multiarmed Bandit"
practica: "Trabajo Práctico 1"
---

```{r}
#| echo: false
#| include: false

is_html <- knitr::is_html_output()
options("knitr.graphics.error" = FALSE)
captions <- list()
captions[["slotmachines2"]] <- "Tres maquinitas con diferentes probabilidades de ganar"
```


# Introducción

<!--
Algunas fuentes:
https://www.conicet.gov.ar/apuestas-online-en-la-adolescencia-y-juventud-una-mirada-desde-lo-biologico-y-lo-social/
https://www.clarin.com/sociedad/nuevo-informe-apuestas-online-afecta-4-10-jovenes-pais-alertan-graves-consecuencias_0_X81rrMQMoH.html?srsltid=AfmBOooKGSu0al0XwGV8oIFnbptb7s64b2KXjCV5vgLquI8FmHxR1yd8
https://ugc.production.linktr.ee/cd2596a8-1dce-4f38-b151-a217d61227f1_informe-resultados-apostar-no-es-un-juego-2024-final-IMPRENTA-v2.pdf
-->

La idea de convertir unos pocos pesos en una fortuna con un solo clic tiene algo de magia, de esa que seduce con la promesa de éxito instantáneo. Masivo. ¿Qué puede salir mal? Total... "Está todo bajo control, yo decido cuándo frenar". El problema es que, a veces de manera silenciosa, el juego compulsivo puede desencadenar problemas de largo plazo en la salud mental y el funcionamiento social del individuo

Las apuestas en línea han ganado una creciente popularidad entre los adolescentes, impulsadas por la accesibilidad de plataformas digitales y la constante exposición a la publicidad en redes sociales y eventos deportivos. A esto se suma que se trata de una actividad escasamente regulada por el Estado y a la que cualquier persona puede acceder con relativa facilidad. 

Estas apuestas pueden dividirse en dos grandes categorías: los casinos virtuales, que incluyen juegos como ruleta o blackjack, y las apuestas deportivas, donde los jóvenes apuestan sobre el resultado de eventos deportivos, a menudo influenciados por pronósticos y estrategias compartidas en comunidades en línea. Ambas modalidades presentan riesgos relevantes, ya que la facilidad para depositar dinero y la sensación de control pueden llevar a un espiral de pérdidas y nuevas apuestas en busca de recuperar lo perdido. 

La sensación de ganar y perder plata genera adrenalina. La adolescencia, una etapa crucial de desarrollo de los seres humanos, es especialmente susceptible a la promesa del dinero fácil y a la gratificación instantánea que pueden otorgar los juegos de apuestas, debido a la inmadurez de las áreas cerebrales encargadas del control de impulsos, lo que incrementa la vulnerabilidad a comportamientos adictivos. A esto se suman factores sociales como la presión de grupo y la búsqueda de aceptación, donde ganar una apuesta se convierte en una forma de demostrar conocimiento y obtener reputación entre pares. 

La ilusión de ganar dinero rápido, junto con la normalización de las apuestas a través de la publicidad, crea un cóctel peligroso que atrapa a los jóvenes en un ciclo de riesgo y compulsión. A esto se suma la aparición de gurúes financieros y esquemas piramidales que prometen riqueza rápida, donde quienes no participan son vistos como ingenuos o fracasados. Esta presión social y la promesa de ganancias fáciles refuerzan la participación en un entorno cada vez más riesgoso y manipulador.

Como si todo esto fuera poco, indagar en un grupo sobre temas sensibles puede resultar complejo. Muchas personas, por vergüenza, miedo al juicio social o simplemente por desconfianza, optan por no responder con sinceridad a ciertas preguntas, por ejemplo en el marco de una encuesta. En el caso de las apuestas, admitir la frecuencia con la que se participa, las cantidades apostadas o las pérdidas sufridas puede generar resistencia a contestar con la verdad. Algunas personas evitan responder, mientras que otras pueden proporcionar respuestas erróneas de manera deliberada. Este fenómeno, conocido como sesgo de respuesta, representa un desafío para quienes buscan obtener datos fiables en encuestas y estudios sobre este tema.

Partiendo de la premisa de que una forma de incrementar la cooperación de los encuestados es garantizar la protección de información sensible, una posible forma de mitigar este sesgo es la técnica de respuesta aleatorizada, que permite que los encuestados respondan de manera más sincera sin temor a ser identificados. En la técnica de respuesta aleatorizada, se introduce una cuota de azar con el objetivo de preservar la privacidad de la persona que responde. 

Nos centraremos en el problema de querer realizar inferencias sobre $\pi_A$ la proporción de estudiantes de una escuela que participan de apuestas deportivas en línea. 

Estudiaremos dos técnicas de respuesta aleatorizada. En lugar de de responder directamente a la pregunta _"¿Participaste alguna vez en apuestas deportivas en línea?"_, se le pide al encuestado que utilice un mecanismo aleatorio, como arrojar una moneda. Dependiendo del resultado de este mecanismo, el encuestado sigue ciertas instrucciones para responder. En las variantes que estudiaremos, por ejemplo, si sale cara, el estudiante contesta a la pregunta _"¿Participaste alguna vez en apuestas deportivas en línea?"_ mientras que si sale cruz, responde a otra pregunta. Así, como el investigador no conoce el resultado del mecanismo aleatorio no puede saber a qué pregunta está respondiendo el encuestado. No obstante, a partir de los resultados obtenidos para toda la muestra, pueden obtenerse conclusiones válidas. 

En el caso más general, diremos que $p$ es la probabilidad (conocida), debida al mecanismo aleatorio, de que el encuestado responda a la pregunta _"¿Participaste alguna vez en apuestas deportivas en línea?"_ mientras que $(1-p)$ es la probabilidad de que responda a la otra pregunta.

# Técnicas de respuesta aleatorizada

## Warner

Un mecanismo aleatorio selecciona la pregunta que se le presenta a la persona que responde. Con probabilidad $p$ se le pregunta si es cierto que alguna vez participó en apuestas deportivas en línea ($Q_1$), mientras que con probabilidad $(1-p)$ se le pregunta si es cierto que nunca participó en apuestas deportivas en línea ($Q_2$). Es decir, en general, con probabilidad $p$ se le pregunta si pertenece a una categoría $A$, mientras que con probabilidad $(1-p)$ se le pregunta si pertenece a la categoría $A^c$ (el complemento de $A$).

## Greenberg y otros

Un mecanismo aleatorio selecciona la pregunta que se le presenta a la persona que responde. Con probabilidad $p$ se le pregunta si es cierto que alguna vez participó en apuestas deportivas en línea ($Q_1$), mientras que con probabilidad $(1-p)$ se le pregunta si nació en un mes de 31 días ($Q_2$). Es decir, en general, con probabilidad $p$ se le pregunta si pertenece a una categoría $A$, mientras que con probabilidad $(1-p)$ se le pregunta si pertenece a una categoría $B$ (no controversial o no polémica).

Existen dos versiones de esta modalidad, en relación al conocimiento o desconocimiento de $\pi_B$, la proporción de elementos en la población que pertenece a la categoría $B$. En el primer caso, se conoce de antemano $\pi_B$ (como en el caso presentado, en que $\pi_B = \frac{7}{12}$). Mientras que en el segundo caso, no se conoce $\pi_B$. Nos limitaremos al estudio de la primera situación.

# Actividades

Para todo lo que sigue, tenga en consideración lo siguiente:
    - Se toma una muestra al azar con reemplazo de tamaño $n=100$ de una población de tamaño $N=1000$ (esto se podría omitir)
    - Para nuestros estudios comparativos, supondremos que el porcentaje de alumnos que apuesta (lo que se quisiera estimar) es 40%
    - Cuando se les pregunta directamente si han hecho alguna vez apuestas, los estudiantes mienten con probabilidad $\mu$
    - Si se utilizan técnicas de respuesta aleatorizada, los estudiantes no mienten
    
    
    
Comenzaremos realizando un estudio de simulación para estudiar el efecto de la mentira en las estimaciones. En esta primera aproximación, consideraremos que se realiza la pregunta directa.

    1. Proponga un modelo bayesiano que, a partir de encuestar a $n$ estudiantes, permita estimar $\pi_a$. Explique la elección de la función de verosimilitud y el _prior_ e indique cómo se obtiene el _posterior_.
    2. Utilizando R, simule la obtención de una muestra para el caso en que los estudiantes no mienten y para el caso en que los estudiantes mienten con tres niveles de mentira $\mu$: bajo, alto y medio. Compare los resultados de la inferencia.
    3. Realice ahora 1000 simulaciones y compare los resultados de las inferencias. 
    
Considere ahora el caso del método propuesto por Werner:

    4. Según este método, ¿cuál es la probabilidad (llamémosla $\lambda_W$) de que un estudiante responda que apuesta? ¿cuál es la probabilidad de que un estudiante           responda que no apuesta?
    5. A partir de lo anterior, proponga un modelo razonable sobre cómo se generan los datos
    6. Considere un _prior_ uniforme y halle el _posterior_ exacto.

    ::: {.callout-tip}
    ## Ayuda
    
    Escriba el _posterior_ dejando el denominador de la Regla de Bayes expresado como $Z$. Luego, muestre que:
    
    $$Z = \frac{B(1-p;y+1,n-y+1) - B(p;y+1,n-y+1)}{1-2p}$$
    
    donde $B(x; a,b) = \int_0^x t^{a-1} (1-t)^{b-1} dt$ es la función beta incompleta, $p$ es la probabilidad con la que se hace la pregunta alternativa e $y$ es la         cantidad de personas que responden que apuestan.
    
    Para resolver la integral, utilice el método de sustitución y hágalo en términos de $\lambda_W$. No es tan terrible como parece.
    :::
    
    7. Grafique el _posterior_ para diferentes valores de $p$ y concluya.
    8. ¿Qué pasaría si el porcentaje de alumnos que apuesta fuera diferente al $40\%$? Analice los resultados en función de diferentes niveles de $p$ y $\pi_a$
    9. Escriba una función de R que le permita realizar la inferencia (en forma aproximada) con un _prior_ beta no necesariamente uniforme

Para el método propuesto por Greenberg:

    10. ¿Cuál es la probabilidad $\lambda_G$ de que un estudiante responda que apuesta? ¿y de que responda que no apuesta?
    11. Escriba una función de R que le permita realizar la inferencia (en forma aproximada) con un _prior_ beta no necesariamente uniforme
    
Para terminar, es hora de comparar todos los escenarios

    12. Utilizando R, simule la obtención de una muestra para el caso en que los estudiantes no mienten, mienten con tres niveles de mentira $\mu$ (bajo, alto y medio),     se utiliza el método de Werner y se utiliza el método de Greenberg. Compare los resultados de las inferencias en cada caso.
    13. Realice ahora 1000 simulaciones y analice los resultados. 


    

    
    
    

Cosas que quisiera preguntar:
    - ¿por qué es válido utilizar una verosimilitud binomial?
    - para el caso de Werner, considerar un _prior_ uniforme y obtener el posterior exacto (hay que integrar el numerador, podemos darles unas pistas para que lo hagan, es lo que hace McElreath).
    - pedirles que escriban la función que simula la respuesta genuina, la respuesta con mentira, la respuesta con Werner y la respuesta con Greenberg
    
    
## Posibles tareas

* Medir el sesgo en la estimación para diferentes cantidad de encuestados,
diferentes niveles de mentira, y diferentes valores del parámetro de interés.
    * Tal vez sea mucho, y aburrido.
* Técnica 1
    * Determinar $\lambda$ en función de $p$ y $\pi$
    * Expresar el modelo bayesiano
        * Escribir función de verosimilitud en función de $\pi$.
    * Dado un escenario, obtener el posterior
    * Comparar con:
        * El resultado obtenido mediante pregunta directa, usando un modelo beta-binomial y que las personas no mienten.
        * El resultado obtenido mediante pregunta directa, usando un modelo beta-binomial y que las personas mienten en un grado leve, moderado y alto. Las personas mienten cuando tienen la característica de interés, con una probabilidad determinadad (e.g. 25%, 50% y 75%).
* Técnica 2
    * Determinar $\lambda$ en función de $p$ y $\pi$
    * Expresar el modelo bayesiano
        * Escribir función de verosimilitud en función de $\pi$.
    * Dado un escenario, obtener el posterior
    * Comparar con:
        * El resultado obtenido mediante pregunta directa, usando un modelo beta-binomial y que las personas no mienten.
        * El resultado obtenido mediante pregunta directa, usando un modelo beta-binomial y que las personas mienten en un grado leve, moderado y alto.
        Las personas mienten cuando tienen la característica de interés, con una probabilidad determinadad (e.g. 25%, 50% y 75%).
    * ¿Qué escenario conviene más, uno donde $\pi_y$ sea bajo, moderado, o alto?
* Comparar inferencias entre sí.


$$
f(\pi | r, n) \propto \pi^{\alpha - 1} (1 - \pi)^{\beta - 1} 
\left[ (2p - 1) \pi + (1 - p) \right]^r \left[ p - (2p - 1) \pi \right]^{n - r}
$$




$$
f(\pi | r, n) = \sum_{t=0}^{n} w_t f_{\beta} (\pi \mid \alpha + t, \beta + n - t)
$$

$$
w_t = \frac{w_t^*}{\sum_{s=0}^{n} w_s^*}
$$

y

$$
w_t^* = \binom{n}{t} \frac{B(\alpha' + t, \beta' + n - t)}{B(\alpha', \beta')}
\sum_{j=0}^{\min(r,t)} \binom{t}{j} \binom{n - t}{r - j} p^{n - t - r + 2j} (1 - p)^{t + r - 2j}.
$$

