project:
  type: website
  preview:
    port: 4200

website:
  title: "Estadística Bayesiana"
  description: "Página del curso Estadística Bayesiana - Licenciatura en Estadística (UNR)."
  site-url: "https://estadisticaunr.github.io/estadistica-bayesiana/"
  favicon: utils/imgs/favicon.png

  navbar:
    pinned: true
    background: "#f07039"
    right:
      - text: Información
        file: info/programa.qmd
      - text: Apuntes
        file: apuntes/introduccion.qmd
      - text: Practica
        file: practica/practica_00.qmd
      - text: Trabajos Practicos
        file: trabajos_practicos/descripcion.qmd
      - text: Cómputo
        file: computo/instalacion.qmd
      - text: Material complementario
        file: complementario/probabilidad.qmd
      - icon: github
        href: "https://github.com/estadisticaunr/estadistica-bayesiana"


  sidebar:
    - title: Información
      style: docked
      search: false
      background: dark
      contents:
        - text: Programa
          file: info/programa.qmd
        - text: Condiciones de aprobación
          file: info/aprobacion.qmd
        - text: Bibliografia
          file: info/bibliografia.qmd
        - text: Docentes
          file: info/docentes.qmd
        - text: Calendario
          file: info/calendario.qmd
        - text: Enlaces útiles
          file: info/enlaces_utiles.qmd
        - text: Preguntas frecuentes
          file: info/faq.qmd
    - title: Practica
      style: docked
      search: false
      background: dark
      contents:
        - text: Unidad 0
          file: practica/practica_00.qmd
        - text: Unidad 1
          file: practica/practica_01.qmd
        - text: Unidad 2
          file: practica/practica_02.qmd
        - text: Unidad 3
          file: practica/practica_03.qmd
    - title: Trabajos Practicos
      style: docked
      search: false
      background: dark
      contents:
        - text: Descripción
          file: trabajos_practicos/descripcion.qmd
        - text: Trabajo 0
          file: trabajos_practicos/00_tp0.qmd
        - text: Trabajo 1
          file: trabajos_practicos/01_tp1.qmd
        - text: Trabajo 2
          file: trabajos_practicos/02_tp2.qmd
        - text: Trabajo 3
          file: trabajos_practicos/03_tp3.qmd
    - title: Cómputo
      style: docked
      search: false
      background: dark
      contents:
        - text: Instalación
          file: computo/instalacion.qmd
    - title: Material complementario
      style: docked
      search: false
      background: dark
      contents:
        - text: Probabilidad
          file: complementario/probabilidad.qmd

  page-footer:
    right: "Esta página es hecha con ❤️ y [Quarto](https://quarto.org/)."

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    lang: es
