project:
  type: website
  preview:
    port: 4200

website:
  title: "Estadística Bayesiana"
  description: "Página del curso Estadística Bayesiana - Licenciatura en Estadística (UNR)."
  site-url: "https://estadisticaunr.github.io/estadistica-bayesiana/"
  favicon: utils/imgs/favicon.png

  navbar:
    pinned: true
    background: "#f07039"
    right:
      - text: Información
        file: info/programa.qmd
      # - text: Apuntes
      #   file: apuntes/introduccion.qmd
      - text: Práctica
        file: practica/practica_00.qmd
      - text: Trabajos Prácticos
        file: trabajos_practicos/descripcion.qmd
      # - text: Cómputo
      #   file: computo/instalacion.qmd
      # - text: Material complementario
      #   file: complementario/probabilidad.qmd
      - icon: github
        href: "https://github.com/estadisticaunr/estadistica-bayesiana"


  sidebar:
    - title: Información
      style: docked
      search: false
      background: dark
      contents:
        - text: Programa
          file: info/programa.qmd
        - text: Condiciones de aprobación
          file: info/aprobacion.qmd
        - text: Bibliografia
          file: info/bibliografia.qmd
        - text: Docentes
          file: info/docentes.qmd
        - text: Calendario
          file: info/calendario.qmd
        - text: Enlaces útiles
          file: info/enlaces_utiles.qmd
        - text: Preguntas frecuentes
          file: info/faq.qmd
    - title: Práctica
      style: docked
      search: false
      background: dark
      contents:
        - text: Unidad 0
          file: practica/practica_00.qmd
        - text: Unidad 1
          file: practica/practica_01.qmd
        - text: Unidad 2
          file: practica/practica_02.qmd
        - text: Unidad 3
          file: practica/practica_03.qmd
        - text: Unidad 4
          file: practica/practica_04.qmd
        - text: Unidad 5
          file: practica/practica_05.qmd
    - title: Trabajos Prácticos
      style: docked
      search: false
      background: dark
      contents:
        - text: Generalidades
          file: trabajos_practicos/descripcion.qmd
        - text: TP 1
          file: trabajos_practicos/01_tp1.qmd
        - text: TP 2
          file: trabajos_practicos/02_tp2.qmd
        - text: TP 3
          file: trabajos_practicos/03_tp3.qmd
    - title: Cómputo
      style: docked
      search: false
      background: dark
      contents:
        - text: Instalación
          file: computo/instalacion.qmd
    - title: Material complementario
      style: docked
      search: false
      background: dark
      contents:
        - text: Probabilidad
          file: complementario/probabilidad.qmd
        - text: Variables aleatorias y distribuciones de probabilidad
          file: complementario/variables.qmd

  page-footer:
    right: "Esta página es hecha con ❤️ y [Quarto](https://quarto.org/)."

bibliography: references.bib
csl: chicago-author-date.csl

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    lang: es
