project:
  type: website
  preview:
    port: 4200
  post-render: 
    - ../scripts/copy_imgs.R

website:
  title: "Estadística Bayesiana"
  description: "Página del curso Estadística Bayesiana - Licenciatura en Estadística (UNR)."
  site-url: "https://estadisticaunr.github.io/estadistica-bayesiana/"

  page-footer:
    right: "Esta página es hecha con ❤️ y [Quarto](https://quarto.org/)."

  sidebar:
    pinned: True
    align: center
    tools:
      - icon: github
        href: https://github.com/estadisticaunr/estadistica-bayesiana
    style: "docked"
    search: true
    collapse-level: 1
    contents:
    - section: "Información del curso"
      contents:
        - href: index.qmd
          text: Descripción
        - href: info/programa.qmd
          text: Programa
        - href: info/bibliografia.qmd
          text: Bibliografia
        - href: info/docentes.qmd
          text: Docentes
        - href: info/calendario.qmd
          text: Calendario
        - href: info/enlaces_utiles.qmd
          text: Enlaces útiles
        - href: info/faq.qmd
          text: Preguntas frecuentes
    - section: "Apuntes"
      contents:
        - href: apuntes/introduccion.qmd
          text: "Introduccion"
    - section: "Práctica"
      contents:
        - href: practica/practica_00.qmd
          text: "Unidad 0"
        - href: practica/practica_01.qmd
          text: "Unidad 1"
        - href: practica/practica_02.qmd
          text: "Unidad 2"
    - section: "Proyecto"
      contents:
        - href: proyecto/descripcion.qmd
          text: Descripción
        - href: proyecto/recursos.qmd
          text: Recursos
    - section: "Cómputo"
      contents:
        - href: computo/instalacion.qmd
          text: Instalación
    - section: "Material complementario"
      contents:
        - href: complementario/probabilidad.qmd
          text: Probabilidad

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: es
