on:
  push:
    branches: main

name: Renderizar y publicar página web

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Generate es_AR locale # Lo usamos en el calendario
        shell: bash
        run: |
          sudo apt-get update 
          sudo apt-get install tzdata locales -y 
          sudo locale-gen es_AR.UTF-8
          locale -a

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::dplyr
            any::ggplot2
            any::ggquiver
            any::googlesheets4
            any::here
            any::kableExtra
            any::knitr
            any::latex2exp
            any::mvtnorm
            any::patchwork
            any::readr
            any::rmarkdown
            any::tidyr
            any::viridis

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2   
        with:
          version: 1.2.280 
      
      # Ver: https://github.com/quarto-dev/quarto-actions/issues/41
      # Importante renderizar las presentaciones, luego son linkeadas en la página
      - name: Render Webpage
        shell: bash
        run: |
          quarto render --to html --output-dir _site
          quarto render presentaciones 

      - name: Publish to GitHub 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          path: _site

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}