on:
  push:
    branches: main

name: Renderizar PDF de la practica

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        run: R -e 'install.packages(c("here", "rmarkdown", "knitr"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2  

      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Install TinyTex.   
        run: quarto install tinytex

      - name : Run script to create PDF files
        run: Rscript scripts/render_pdf.R

      - name : Publish to 'pdf' branch
        shell: bash
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b pdf
          mv .output/practica/*.pdf practica/
          git rm -rf '*'
          git add practica/*.pdf
          git commit -m "Render PDFs"
          git push origin pdf --force
