on:
  push:
    branches: main

name: Renderizar y publicar página web

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Generate es_AR locale # Lo usamos en el calendario
        shell: bash
        run: |
          sudo apt-get update 
          sudo apt-get install tzdata locales -y 
          sudo locale-gen es_AR.UTF-8

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::dplyr
            any::ggplot2
            any::here
            any::kableExtra
            any::knitr
            any::latex2exp
            any::mvtnorm
            any::patchwork
            any::readr
            any::rmarkdown
            any::tidyr
            any::viridis

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2    
        
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}